Feature/dsnd 1455 upsert company metrics with appointment counts
companieshouse/company-metrics-api pull request #46
Opened 2023-02-21 16:15 UTC by johncook-ch

* Refactored ChargesRepository to use MongoDB aggregations
* Implemented a MongoDB aggregation to retrieve appointments metrics in once call.
* Implemented the AppointmentsCountService and associated model classes and repository.
* Tidied up unit tests where the names were ambiguous now that the metrics API handles more than just charges.

_Testers please not: There have been changes to the implementation of charges metrics so these also need to be checked_

2023-02-23 12:13 UTC, sthompsonCH approved these changes

2023-02-23 14:25 UTC, kinpang-CH submitted a review, later dismissed

2023-02-23 15:53 UTC, sthompsonCH approved these changes

2023-02-23 16:06 UTC, kinpang-CH approved these changes

2023-02-27 09:16 UTC, kinpang-CH submitted a review, later dismissed

2023-02-27 10:34 UTC, kinpang-CH submitted a review, later dismissed

2023-02-27 10:40 UTC, sthompsonCH submitted a review, later dismissed

2023-02-27 11:44 UTC, sthompsonCH submitted a review, later dismissed

2023-02-27 11:44 UTC, crowlandsCH requested changes

2023-02-27 13:53 UTC, johncook-ch commented on src/main/java/uk/gov/companieshouse/company/metrics/service/CompanyMetricsService.java
> +
The whitespace here to aid readability.

2023-02-27 14:41 UTC, crowlandsCH approved these changes

2023-02-27 14:56 UTC, kinpang-CH approved these changes

2023-02-28 10:05 UTC, sthompsonCH approved these changes

2023-02-28 11:08 UTC, cgregoryCH approved these changes

2023-02-28 11:27 UTC, merged